# Generated by Django 3.2.8 on 2021-11-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_creditcardtips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creditcardtips',
            new_name='credit_tips',
        ),
    ]
