# Generated by Django 3.2.8 on 2021-11-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_creditcardtips_event_credit_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='credit_tips_reduced',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
