# Generated by Django 3.2.8 on 2021-11-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('events', '0007_event_credit_tips_reduced'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcustomer',
            name='per_customer_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventcustomer',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='customer_product', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventstaff',
            name='event_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_product', to='products.product'),
        ),
        migrations.AddField(
            model_name='eventstaff',
            name='event_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventstaff',
            name='prepaint_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepaint_product', to='products.product'),
        ),
        migrations.AddField(
            model_name='eventstaff',
            name='prepaint_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
