# Generated by Django 3.2.8 on 2021-11-04 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('events', '0008_auto_20211104_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcustomer',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='customer_product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='eventstaff',
            name='event_product',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='eventstaff',
            name='prepaint_product',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepaint_product', to='products.product'),
        ),
    ]
