# Generated by Django 3.2.8 on 2021-11-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20211104_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcustomer',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
