# Generated by Django 3.2.8 on 2021-11-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20211106_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='hourly_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='eventstaff',
            name='prepaint_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
