# Generated by Django 3.2.8 on 2021-11-06 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20211106_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('i', 'Internal Event'), ('p', 'Paint Pour Event'), ('w', 'Painting with a Purpose Event'), ('r', 'Retail Only'), ('s', 'Standard Event'), ('t', 'Other Tax Free Event')], default='s', max_length=1),
        ),
    ]
