# Generated by Django 3.2.8 on 2021-11-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcustomer',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='eventcustomer',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
