# Generated by Django 3.2.8 on 2021-11-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20211106_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcustomer',
            name='cost_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
