# Generated by Django 3.2.8 on 2021-11-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventcustomer_total_customer_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='total_staff_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
