# Generated by Django 3.2.8 on 2021-11-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_eventstaff_total_staff_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstaff',
            name='total_staff_qty',
        ),
    ]
