# Generated by Django 3.2.8 on 2021-11-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_eventstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='status',
            field=models.CharField(choices=[('p', 'Pending Processing'), ('c', 'Completed Processing')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='eventstaff',
            name='role',
            field=models.CharField(choices=[('f', 'Floor Artist'), ('s', 'Stage Artist'), ('t', 'Team Member')], default='s', max_length=1),
        ),
    ]
