# Generated by Django 3.2.8 on 2021-11-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20211108_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcustomer',
            name='status',
            field=models.CharField(choices=[('p', 'Pending Processing'), ('c', 'Completed Processing')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='eventstaff',
            name='status',
            field=models.CharField(choices=[('p', 'Pending Processing'), ('a', 'Approved for Payment'), ('c', 'Completed Processing')], default='p', max_length=1),
        ),
    ]
