# Generated by Django 3.2.8 on 2021-11-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20211108_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='z', max_length=1),
        ),
        migrations.AlterField(
            model_name='eventstaff',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('c', 'Completed')], default='p', max_length=1),
        ),
    ]
