# Generated by Django 3.2.8 on 2021-11-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('royaltyreports', '0003_auto_20211109_1131'),
        ('events', '0025_auto_20211108_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='royalty_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='royaltyreports.report'),
        ),
    ]
