# Generated by Django 3.2.8 on 2021-11-10 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0026_event_royalty_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Completed')], default='p', max_length=1),
        ),
        migrations.CreateModel(
            name='EventTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('split', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
