# Generated by Django 3.2.8 on 2021-11-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20211110_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtip',
            old_name='split_stage',
            new_name='floor_split',
        ),
        migrations.AddField(
            model_name='eventtip',
            name='stage_split',
            field=models.DecimalField(decimal_places=2, default=0.7, max_digits=3),
        ),
    ]
