# Generated by Django 3.2.8 on 2021-11-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20211110_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtip',
            name='user',
        ),
    ]
