# Generated by Django 3.2.8 on 2021-11-10 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_remove_eventtip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtip',
            name='credit_fee',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=2),
        ),
        migrations.AddField(
            model_name='eventtip',
            name='floor_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='eventtip',
            name='stage_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='eventtip',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('c', 'Completed')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='eventtip',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtip',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
