# Generated by Django 3.2.8 on 2021-11-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20211110_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='credit_tips',
        ),
        migrations.RemoveField(
            model_name='event',
            name='credit_tips_reduced',
        ),
    ]
