# Generated by Django 3.2.8 on 2021-11-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20211110_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payroll_status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Completed')], default='p', max_length=1),
        ),
    ]
