# Generated by Django 3.2.8 on 2021-11-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_event_payroll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='commission_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='eventstaff',
            name='tip_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
