# Generated by Django 3.2.8 on 2021-11-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_commissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commissions',
        ),
    ]
