# Generated by Django 3.2.8 on 2021-11-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payreport_staff_count'),
        ('events', '0036_delete_commissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payroll_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payreport'),
        ),
    ]
