# Generated by Django 3.2.8 on 2021-11-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_event_payroll_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstaff',
            options={},
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='19:00:00'),
        ),
    ]
