# Generated by Django 3.2.8 on 2021-11-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_purchaseitem_date'),
        ('events', '0039_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaff',
            name='event_product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='eventstaff',
            name='prepaint_product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepaint_product', to='products.product'),
        ),
    ]
