# Generated by Django 3.2.8 on 2021-11-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_purchaseitem_date'),
        ('events', '0040_auto_20211127_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcustomer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_product', to='products.product'),
        ),
    ]
