# Generated by Django 3.2.8 on 2021-11-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_alter_eventcustomer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstaff',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
