# Generated by Django 3.2.8 on 2021-11-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_alter_eventstaff_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='typical_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
