# Generated by Django 3.2.8 on 2021-12-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxreports', '0002_auto_20211202_0818'),
        ('events', '0045_auto_20211201_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tax_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxreports.taxreport'),
        ),
    ]
