# Generated by Django 3.2.8 on 2021-12-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_event_tax_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcustomer',
            name='cost_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
