# Generated by Django 3.2.8 on 2021-12-02 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_alter_eventcustomer_cost_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcustomer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
