# Generated by Django 3.2.8 on 2021-12-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_eventimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimages',
            old_name='filename',
            new_name='title',
        ),
    ]
