# Generated by Django 3.2.8 on 2021-12-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_eventimages_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='cost_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
