# Generated by Django 3.2.8 on 2021-12-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_eventstaff_cost_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcustomer',
            name='product_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
