# Generated by Django 3.2.8 on 2022-01-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_eventcustomer_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
