# Generated by Django 3.2.8 on 2022-01-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_adminpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpay',
            name='note',
            field=models.CharField(default='Management Adjustment', max_length=50),
        ),
    ]
