# Generated by Django 3.2.8 on 2022-07-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_alter_eventcustomer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstaff',
            name='staff_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
