# Generated by Django 3.2.8 on 2021-11-07 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date', '-publish_time']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='publish',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
