# Generated by Django 3.2.8 on 2021-11-07 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20211106_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
