# Generated by Django 3.2.8 on 2021-11-07 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20211106_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publish_time',
        ),
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
