# Generated by Django 3.2.8 on 2021-11-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp']},
        ),
    ]
