# Generated by Django 3.2.8 on 2021-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
