# Generated by Django 3.2.8 on 2021-12-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seen_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
