# Generated by Django 3.2.8 on 2021-12-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_article_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='email_status',
            field=models.CharField(choices=[('n', 'Not Sent'), ('s', 'Sent')], default='n', max_length=1),
        ),
    ]
