# Generated by Django 3.2.8 on 2021-12-02 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('eventcustomer_cost_factors', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('eventcustomer_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('square_retail_sales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('squaresales_taxes', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Abandoned'), ('c', 'Completed')], default='p', max_length=1)),
                ('prev_status', models.CharField(choices=[('p', 'Pending'), ('a', 'Abandoned'), ('c', 'Completed')], default=None, max_length=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
