# Generated by Django 3.2.8 on 2021-12-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxreports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreport',
            name='total_taxable_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='taxreport',
            name='total_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='taxreport',
            name='eventcustomer_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='taxreport',
            name='square_retail_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='taxreport',
            name='squaresales_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
