# Generated by Django 3.2.8 on 2022-04-02 10:32

import activities.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0003_payreport_staff_count'),
        ('taxreports', '0002_auto_20211202_0818'),
        ('royaltyreports', '0008_rename_square_retail_sales_tax_royaltyreport_square_retail_sales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_alter_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Time Entry', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('a', 'Artist Training'), ('x', 'Customer eXperience'), ('o', 'General Office Work')], default='x', max_length=1)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('c', 'Completed')], default='p', max_length=1)),
                ('payroll_status', models.CharField(choices=[('p', 'Pending'), ('c', 'Completed')], default='p', max_length=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_created_by', to=settings.AUTH_USER_MODEL)),
                ('payroll_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payreport')),
                ('royalty_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='royaltyreports.royaltyreport')),
                ('tax_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxreports.taxreport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('staff_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('credit_fee', models.DecimalField(decimal_places=2, default=0.03, max_digits=2)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('c', 'Completed')], default='p', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('f', 'Floor Artist'), ('t', 'Team Member'), ('c', 'Customer eXperience')], default='c', max_length=1)),
                ('hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('prepaint_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('hourly_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tip_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('commission_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('prepaint_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('activity_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('cost_factor', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('c', 'Completed')], default='p', max_length=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('activity_product', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_product', to='products.product')),
                ('prepaint_product', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_prepaint_product', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('upload', models.ImageField(upload_to=activities.models.activity_image_upload_handler)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('h', 'Twist at Home Kit(s) / Pop-In & Paint')], default='h', max_length=1)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('per_customer_qty', models.IntegerField(default=1)),
                ('total_customer_qty', models.IntegerField(default=0)),
                ('subtotal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cost_factor', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('product_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('status', models.CharField(choices=[('p', 'Pending Processing'), ('c', 'Completed Processing')], default='p', max_length=1)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_customer_product', to='products.product')),
            ],
            options={
                'ordering': ['-type', '-quantity'],
            },
        ),
        migrations.CreateModel(
            name='ActivitiesAdminPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('c', 'Completed')], default='p', max_length=1)),
                ('note', models.CharField(default='Add Justification Note', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
