# Generated by Django 3.2.8 on 2022-04-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_activitiesadminpay_activityadminpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
