# Generated by Django 3.2.8 on 2022-04-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
