# Generated by Django 3.2.8 on 2022-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20220408_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('f', 'Artist Training'), ('c', 'Customer eXperience'), ('t', 'General Office Work')], default='f', max_length=1),
        ),
    ]
