# Generated by Django 3.2.8 on 2021-11-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('time_zone', models.CharField(max_length=50)),
                ('gross_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('discounts', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('net_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('gift_card_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tip', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('partial_refunds', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('source', models.CharField(max_length=50)),
                ('card', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('card_entry_methods', models.CharField(max_length=50)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('square_gift_card', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('other_tender', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('other_tender_note', models.CharField(max_length=50)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('transaction_id', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('card_brand', models.CharField(max_length=50)),
                ('pan_suffix', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=50)),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('description', models.TextField()),
                ('event_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('dining_option', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_reference_id', models.CharField(max_length=50)),
                ('device_nickname', models.CharField(max_length=50)),
                ('deposit_id', models.CharField(max_length=50)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('deposit_details', models.TextField()),
                ('fee_percentage_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fee_fixed_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('refund_reason', models.CharField(max_length=50)),
                ('discount_name', models.CharField(max_length=50)),
                ('transaction_status', models.CharField(max_length=50)),
                ('order_reference_id', models.CharField(max_length=50)),
            ],
        ),
    ]
