# Generated by Django 3.2.8 on 2021-11-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
