# Generated by Django 3.2.8 on 2021-11-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0002_alter_square_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='other_tender_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
