# Generated by Django 3.2.8 on 2021-12-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0004_auto_20211128_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='taxable_sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
