# Generated by Django 3.2.8 on 2021-12-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0005_square_taxable_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('a', 'Abandoned'), ('c', 'Completed')], default='p', max_length=1),
        ),
    ]
