# Generated by Django 3.2.8 on 2022-01-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0006_square_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='square',
            name='payment_id',
            field=models.TextField(),
        ),
    ]
