# Generated by Django 3.2.8 on 2021-11-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211105_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact_number_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact_number_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
