# Generated by Django 3.2.8 on 2021-11-06 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20211105_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('stage', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('floor', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('team', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
