# Generated by Django 3.2.8 on 2021-11-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
