# Generated by Django 3.2.8 on 2021-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userpay_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpay',
            name='prepaint_double',
            field=models.DecimalField(decimal_places=2, default=19.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='userpay',
            name='prepaint_single',
            field=models.DecimalField(decimal_places=2, default=13.0, max_digits=4),
        ),
    ]
