# Generated by Django 3.2.8 on 2021-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userpay_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpay',
            name='stage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
