# Generated by Django 3.2.8 on 2021-11-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userpay_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin',
            field=models.IntegerField(default=3444),
        ),
    ]
