# Generated by Django 3.2.8 on 2021-12-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
