# Generated by Django 3.2.8 on 2021-12-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_last_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_url',
        ),
    ]
