# Generated by Django 3.2.8 on 2022-04-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_userprofile_last_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpay',
            name='customer_experience',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
