# Generated by Django 3.2.8 on 2022-04-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_filecategory_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
