# Generated by Django 3.2.8 on 2021-11-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
