# Generated by Django 3.2.8 on 2022-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20220409_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typicalschedule',
            name='sunday',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
