# Generated by Django 3.2.8 on 2022-04-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20220409_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typicalschedule',
            name='friday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='monday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='saturday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='sunday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='thursday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='tuesday',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='wednesday',
            field=models.IntegerField(default=0),
        ),
    ]
