# Generated by Django 3.2.8 on 2022-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20220409_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typicalschedule',
            name='friday_recurrence',
            field=models.CharField(choices=[('w', 'Weekly'), ('b', 'Bi-Weekly'), ('m', 'Once a Month'), ('a', 'Maybe, Ask Me')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='monday_recurrence',
            field=models.CharField(choices=[('w', 'Weekly'), ('b', 'Bi-Weekly'), ('m', 'Once a Month'), ('a', 'Maybe, Ask Me')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='notes',
            field=models.TextField(blank=True, default='I prefer to work X events per week.  I may be able to cover some private parties on week nights and weekends outside of my normal schedule. Just ask.', null=True),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='saturday_recurrence',
            field=models.CharField(choices=[('w', 'Weekly'), ('b', 'Bi-Weekly'), ('m', 'Once a Month'), ('a', 'Maybe, Ask Me')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='sunday_recurrence',
            field=models.CharField(choices=[('w', 'Weekly'), ('b', 'Bi-Weekly'), ('m', 'Once a Month'), ('a', 'Maybe, Ask Me')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='thursday_recurrence',
            field=models.CharField(choices=[('w', 'Weekly'), ('b', 'Bi-Weekly'), ('m', 'Once a Month'), ('a', 'Maybe, Ask Me')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='tuesday_recurrence',
            field=models.CharField(choices=[('w', 'Weekly'), ('b', 'Bi-Weekly'), ('m', 'Once a Month'), ('a', 'Maybe, Ask Me')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='typicalschedule',
            name='wednesday_recurrence',
            field=models.CharField(choices=[('w', 'Weekly'), ('b', 'Bi-Weekly'), ('m', 'Once a Month'), ('a', 'Maybe, Ask Me')], default='w', max_length=1),
        ),
    ]
