# Generated by Django 3.2.8 on 2022-04-14 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0012_alter_schedulechange_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('enddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('p', 'Pending Request'), ('c', 'Approved/Complete'), ('a', 'Aborted Request'), ('d', 'Request Denied')], default='p', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeoff_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeoff_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_approver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
