# Generated by Django 3.2.8 on 2022-04-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_timeoffrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoffrequest',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='timeoffrequest',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
