# Generated by Django 3.2.8 on 2022-04-15 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20220414_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
