# Generated by Django 3.2.8 on 2022-04-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20220415_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='end_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='start_time',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
