# Generated by Django 3.2.8 on 2022-04-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20220415_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoffrequest',
            name='end_time',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
