# Generated by Django 3.2.8 on 2022-04-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_eventpreferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPreferences',
        ),
    ]
