# Generated by Django 3.2.8 on 2021-11-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royaltyreports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
