# Generated by Django 3.2.8 on 2021-11-09 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('royaltyreports', '0002_remove_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='event',
        ),
        migrations.AddField(
            model_name='report',
            name='ad_funds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='report',
            name='adjusted_gross_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='report',
            name='adjustments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='kits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='net_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='report',
            name='reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='royalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='surface_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
