# Generated by Django 3.2.8 on 2021-11-11 18:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_delete_commissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('royaltyreports', '0005_alter_report_surface_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='RoyaltyReport',
        ),
    ]
