# Generated by Django 3.2.8 on 2021-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royaltyreports', '0006_rename_report_royaltyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltyreport',
            name='square_retail_sales_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
