# Generated by Django 3.2.8 on 2021-11-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('royaltyreports', '0007_royaltyreport_square_retail_sales_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='royaltyreport',
            old_name='square_retail_sales_tax',
            new_name='square_retail_sales',
        ),
    ]
