# Generated by Django 3.2.8 on 2021-11-10 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('pay_date', models.DateField(default=django.utils.timezone.now)),
                ('payroll_gross', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Abandoned'), ('c', 'Completed')], default='p', max_length=1)),
                ('prev_status', models.CharField(choices=[('p', 'Pending'), ('a', 'Abandoned'), ('c', 'Completed')], default=None, max_length=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
