# Generated by Django 3.2.8 on 2021-11-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='PayReport',
        ),
    ]
