# Generated by Django 3.2.8 on 2021-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_rename_report_payreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='payreport',
            name='staff_count',
            field=models.IntegerField(default=0),
        ),
    ]
