# Generated by Django 3.2.8 on 2021-11-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('c', 'Canvas'), ('g', 'Glassware'), ('m', 'Wood Board (MDF)'), ('p', 'Wood Plank'), ('o', 'Other')], default='c', max_length=4)),
                ('low_alert_level', models.IntegerField(default=40)),
            ],
        ),
    ]
