# Generated by Django 3.2.8 on 2021-11-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211105_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('c', 'Canvas'), ('g', 'Glassware'), ('s', 'Screen'), ('m', 'Wood Board (MDF)'), ('p', 'Wood Plank'), ('o', 'Other')], default='c', max_length=4),
        ),
    ]
