# Generated by Django 3.2.8 on 2021-11-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productpurchaseitem_purchaseorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPurchaseItem',
            new_name='PurchaseItem',
        ),
    ]
