# Generated by Django 3.2.8 on 2021-11-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_purchaseitem_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.purchaseorder'),
        ),
    ]
