# Generated by Django 3.2.8 on 2021-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_purchaseitem_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='price_each',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
