# Generated by Django 3.2.8 on 2021-11-06 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211106_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
