# Generated by Django 3.2.8 on 2021-11-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_purchaseitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(choices=[('b', 'Art Boards Direct'), ('a', 'Art Supply Distributors'), ('d', 'Diverse Woodworking'), ('h', 'Hobby Lobby'), ('i', 'Inventory Adjustment'), ('p', 'P. Graham Dunn'), ('t', 'TD Art Supply'), ('o', 'Other')], default='t', max_length=1),
        ),
    ]
