# Generated by Django 3.2.8 on 2022-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('c', 'Canvas'), ('e', 'Ceramic'), ('g', 'Glassware'), ('s', 'Screen'), ('m', 'Wood Board (MDF)'), ('p', 'Wood Plank'), ('o', 'Other'), ('r', 'Retail')], default='c', max_length=4),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.CharField(choices=[('3', '1320 Creative'), ('b', 'Art Boards Direct'), ('a', 'Art Supply Distributors'), ('d', 'Diverse Woodworking'), ('c', 'Chesapeake Ceramics'), ('h', 'Hobby Lobby'), ('i', 'Inventory Adjustment'), ('p', 'P. Graham Dunn'), ('t', 'TD Art Supply'), ('o', 'Other')], default='t', max_length=1),
        ),
    ]
